version: '3'

services:
  database:
    image: mysql:${MYSQL_VERSION:-8.0}-alpine
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-u657129098_wine_not}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_USER: ${MYSQL_USER:-u657129098_wine_not}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Wine_not!test123}
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database_data:
